import type { Laptop } from "./types"

export const laptops: Laptop[] = [
  {
    id: 1,
    name: "ZenBook Pro 14 Duo OLED UX8402, 11th Gen Intel",
    price: 1854,
    originalPrice: 2479,
    image: "/asus-zenbook-pro.png",
    rating: 4.5,
    sold: 100,
    brand: "ASUS",
    processor: "Intel i7",
    ram: "16GB",
    storage: "512GB SSD",
    screen: "14 inch",
    inStock: true,
    freeShipping: true,
    category: "Gaming",
    description: "Powerful dual-screen laptop with OLED display for creative professionals",
    features: ["Dual OLED Display", "Intel i7 11th Gen", "NVIDIA RTX Graphics", "Thunderbolt 4"],
  },
  {
    id: 2,
    name: "VivoBook S 16X OLED M5602, AMD Ryzen 5000H",
    price: 1439,
    originalPrice: 1879,
    image: "/asus-vivobook-laptop.png",
    rating: 4.3,
    sold: 89,
    brand: "ASUS",
    processor: "AMD Ryzen 5",
    ram: "8GB",
    storage: "256GB SSD",
    screen: "16 inch",
    inStock: true,
    freeShipping: true,
    category: "Business",
    description: "Sleek and powerful laptop with stunning OLED display",
    features: ["16-inch OLED Display", "AMD Ryzen 5000H", "Fast SSD Storage", "All-day Battery"],
  },
  {
    id: 3,
    name: "VivoBook 13 Slate OLED T3300, 11th Gen Intel",
    price: 575,
    originalPrice: 799,
    image: "/asus-vivobook-slate.png",
    rating: 4.2,
    sold: 156,
    brand: "ASUS",
    processor: "Intel i5",
    ram: "8GB",
    storage: "128GB SSD",
    screen: "13 inch",
    inStock: false,
    freeShipping: false,
    category: "Ultrabook",
    description: "Versatile 2-in-1 tablet laptop with detachable keyboard",
    features: ["Detachable Design", "OLED Touchscreen", "Lightweight", "Windows 11"],
  },
  {
    id: 4,
    name: "ZenBook Pro 16X OLED UX7602, 11th Gen Intel",
    price: 2237,
    originalPrice: 2849,
    image: "/asus-zenbook-pro-16x.png",
    rating: 4.6,
    sold: 67,
    brand: "ASUS",
    processor: "Intel i9",
    ram: "32GB",
    storage: "1TB SSD",
    screen: "16 inch",
    inStock: true,
    freeShipping: true,
    category: "Professional",
    description: "Ultimate creative workstation with massive OLED display",
    features: ["16-inch 4K OLED", "Intel i9 Processor", "32GB RAM", "Professional Graphics"],
  },
  {
    id: 5,
    name: "ROG Strix Scar 15 G533QS, AMD Ryzen 9",
    price: 5081,
    originalPrice: null,
    image: "/asus-rog-strix-laptop.png",
    rating: 4.7,
    sold: 34,
    brand: "ASUS",
    processor: "AMD Ryzen 9",
    ram: "32GB",
    storage: "2TB SSD",
    screen: "15 inch",
    inStock: true,
    freeShipping: true,
    category: "Gaming",
    description: "High-performance gaming laptop with RGB lighting",
    features: ["AMD Ryzen 9", "RTX 3080", "300Hz Display", "RGB Keyboard"],
  },
  {
    id: 6,
    name: "VivoBook Go 14 E410 (TP1400, 11th Gen Intel)",
    price: 409,
    originalPrice: null,
    image: "/asus-vivobook-go.png",
    rating: 4.1,
    sold: 203,
    brand: "ASUS",
    processor: "Intel i3",
    ram: "4GB",
    storage: "128GB eMMC",
    screen: "14 inch",
    inStock: true,
    freeShipping: false,
    category: "Budget",
    description: "Affordable laptop for everyday computing needs",
    features: ["Lightweight Design", "All-day Battery", "Windows 11", "Affordable Price"],
  },
  {
    id: 7,
    name: "ZenBook 14 Flip OLED UP3404, 11th Gen Intel",
    price: 1450,
    originalPrice: null,
    image: "/asus-zenbook-flip.png",
    rating: 4.4,
    sold: 78,
    brand: "ASUS",
    processor: "Intel i7",
    ram: "16GB",
    storage: "512GB SSD",
    screen: "14 inch",
    inStock: true,
    freeShipping: true,
    category: "2-in-1",
    description: "Convertible laptop with 360-degree hinge and OLED display",
    features: ["360° Flip Design", "OLED Touchscreen", "Intel i7", "Stylus Support"],
  },
  {
    id: 8,
    name: "ProArt StudioBook 16 OLED H7600, 11th Gen Intel",
    price: 2890,
    originalPrice: null,
    image: "/asus-proart-studiobook.png",
    rating: 4.8,
    sold: 23,
    brand: "ASUS",
    processor: "Intel i9",
    ram: "32GB",
    storage: "1TB SSD",
    screen: "16 inch",
    inStock: true,
    freeShipping: true,
    category: "Professional",
    description: "Professional workstation for content creators and designers",
    features: ["Pantone Validated Display", "Intel i9", "Quadro Graphics", "Creator Software"],
  },
]
